//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLICAPHE.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QUANLIQUANANGKEntities : DbContext
    {
        public QUANLIQUANANGKEntities()
            : base("name=QUANLIQUANANGKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<BillInfo> BillInfoes { get; set; }
        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<FoodCategory> FoodCategories { get; set; }
        public virtual DbSet<TableFood> TableFoods { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<TOP_SALES_Result> TOP_SALES(Nullable<int> tOP)
        {
            var tOPParameter = tOP.HasValue ?
                new ObjectParameter("TOP", tOP) :
                new ObjectParameter("TOP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TOP_SALES_Result>("TOP_SALES", tOPParameter);
        }
    }
}
